$(document).ready(function () {
  const songs = [
    { title: "İLK YARI", lyrics: "", tur: "sozsuz", yari: "yari" },
    { title: "BUGÜN BİZE HOŞGELDİNİZ ERENLER", lyrics: " Arzu ederdiniz bir yol görmeye<br> Bugün bize hoş geldiniz Erenler<br> Muhabbet bağından güller dermeye<br> Bugün bize hoş geldiniz Erenler<br> Bugün bize hoş geldiniz Erenler<br> Muhabbet bağından hey dost güller dermeye<br> Bugün bize hoş geldiniz Erenler<br> Bugün bize hoş geldiniz Erenler<br> <br> Hisse alın Çırakman'ın sözünden<br> Zerre kaçmaz Ariflerin gözünden<br> Kemal Atatürk'ün aydın izinden <br> Bugün bize hoş geldiniz Erenler<br> Bugün bize hoş geldiniz Erenler<br> Kemal Atatürk'ün hey dost aydın izinden <br> Bugün bize hoş geldiniz Erenler<br> Bugün bize hoş geldiniz Erenler" },
    { title: "MALUM OLSUN DA SANA", lyrics: " Malum olsun da sana bak ne haldayım<br> Yoksa unuttun mu beni bilmem el gibi<br> Gece gündüz de durmaz ahuzardayım<br> Sazım sızlayan sırma tel gibi" },
    { title: "AHİRİM SENSİN", lyrics: " Cahildim dünyanın rengine kandım<br> Hayale aldandım boşuna yandım<br> Seni ilelebet benimsin sandım<br> Ölürüm sevdiğim zehirim sensin<br> Evvelim sen oldun ahirim sensin<br> <br> Sözüm yok şu benden kırıldığına<br> İdip başka dala sarıldığıma<br> Gönülüm inanmıyor ayrıldığına<br> Gözyaşım sen oldun kahirim sensin<br> Evvelim sen oldun ahirim sensin" },
    { title: "ŞU DAĞLAR KÖMÜRDENDİR", lyrics: "Bu dağlar kömürdendir<br> Geçen gün ömürdendir<br> Bu dağlar kömürdendir<br> Geçen gün ömürdendir<br> Feleğin bir kuşu var<br> Pençesi demirdendir<br> Feleğin bir kuşu var<br> Pençesi demirdendir<br> Hadi leylim leylalım<br> Ben yoluna kurbanım<br> Ya al canım kurtulam<br> Ya ver derdin dermanım<br>                                                                <br> Bu yol Pasin’e gider<br> Döner tersine gider<br> Bu yol Pasin’e gider<br> Döner tersine gider<br> Şurda bir garip ölmüş<br> Kuşlar yasına gider<br> Şurda bir garip ölmüş<br> Kuşlar yasına gider<br> Hadi leylim leylalım<br> Ben yoluna kurbanım<br> Ya al canım kurtulam<br> Ya ver derdin dermanı<br> Hadi leylim leylalım<br> Ben yoluna kurbanım<br> Ya al canım kurtulam<br> Ya ver derdin dermanı" },
    { title: "İŞTE GİDİYORUM ÇEŞMİ SİYAHIM", lyrics: "İşte gidiyorum çeşm-i siyahım <br> İşte gidiyorum çeşm-i siyahım<br> Önümüze dağlar sıralansa da sıralansa da <br> Sermayem derdimdir servetim ahım<br> Karardıkça bahtım karalansa da <br> Sermayem derdimdir servetim ahım<br> Karardıkça bahtım karalansa da<br> <br> Bağladım canımı Haydar zülfün teline <br> Bağladım canımı zülfün teline<br> Sen beni bıraktın elin diline elin diline <br> Güldün Mahzuni'nin berbat haline<br> Mervan'ın elinden parelense de <br> Güldün Mahzuni'nin berbat haline<br> Mervan'ın elinde hey hey parelense de" },
    { title: "YÜCE DAĞ BAŞINDA", lyrics: " Yüce dağ başında yanar bir ışık<br> Düşmüşüm derdine olmuşum aşık<br> Al buğday benizli zülfü dolaşık<br> Dividim kalemim yazarım<br> Böyle bir yavrunun derdi var bende<br> Yar bende oy bende<br> Aha ben gidiyom sen hemen ağla<br> Yan ağla dön ağla<br>                                                              <br> Yüce dağ başından indiremedim<br> Yönünü yönüme döndüremedim<br> Bir yarin aklını kandıramadım<br> Dividim kalemim yazarım<br> Böyle bir yavrunun derdi var bende<br> Yar bende oy bende<br> Aha ben gidiyom sen hemen ağla<br> Yan ağla dön ağla<br> Böyle bir yavrunun derdi var bende<br> Yar bende oy bende<br> İşte ben gidiyom sen hemen ağla<br> Yan ağla dön ağla"},  
    { title: "HASTANE ÖNÜNDE İNCİR AĞACI", lyrics: " Hastane önünde incir ağacı<br> Annem ağacı<br> Doktor bulamadı bana ilacı<br> Annem ilacı<br> Doktor bulamadı bana ilacı<br> Annem ilacı<br> Baştabip geliyor zehirden acı<br> Annem oy acı<br> Garip kaldım yüreğime dert oldu<br> Annem dert oldu<br> Ellerin vatanı bana yurt oldu<br> Annem yurt oldu<br><br> Mezarımı kazın bayıra, düze<br> Annem oy düze<br> Yönünü çevirin sıladan yüze<br> Annem oy yüze<br> Yönünü çevirin sıladan yüze<br> Annem oy yüze<br> Benden selam edin sevdiğinize<br> Sevdiğinize<br> Başına koysun karalar bağlasın<br> Annem bağlasın<br> Gurbet elde kaldım diye ağlasın<br> Annem ağlasın<br> Başına koysun karalar bağlasın<br> Annem bağlasın<br> Gurbet elde kaldım diye ağlasın<br> Annem ağlasın" },
    { title: "EKLEMEDİR KOCA KONAK", lyrics: "Eklemedir koca konak ekleme (aman aman)<br> Nazlı da yârim yine yine geldi aklıma<br> Nasıl edeyim başımdaki sevdaya? (aman aman)<br> Aman aman dostlar yoldan geldim, yorgunum<br> Orta da boylu bir güzele vurgunum<br> Aman aman dostlar yoldan geldim yorgunum<br> Orta da boylu bir güzele vurgunum<br>                                                                 <br> Bizim bağın menekşesi al olur (aman aman)<br> Âlem de sevdiğine de yanar kul olur.<br> Sevdiğini alamayan del olur (aman aman)<br> Aman aman dostlar yoldan geldim, yorgunum<br> Orta da boylu bir güzele vurgunum<br> Aman aman dostlar yoldan geldim yorgunum<br> Orta da boylu bir güzele vurgunum<br> " },
    { title: "ALTIN YÜZÜĞÜM", lyrics: " Altın yüzüğüm kırıldı hey<br> Suya düştü su duruldu hey<br> Dediler yarin de gelmiş<br> İnce de bellerim kırıldı<br> Tel tel tellerine<br> Kurban olam dillerine vay<br> Dediler yarin de gelmiş<br> İnce de bellerim kırıldı<br> Tel tel tellerine<br> Kurban olam dillerine vay<br>                                                           <br> <br> Atımın da nalı yoktur hey<br> Üzerinde çulu yoktur hey<br> Gölbaşı'nda yolu yoktur<br> Git gelemem emmim kızı<br> Tel tel tellerine<br> Kurban olam dillerine vay<br> Gölbaşı'nda yolu yoktur<br> Git gelemem emmim kızı<br> Tel tel tellerine<br> Kurban olam dillerine vay" },
    { title: "ESKİ EVİN MERTEĞİ", lyrics: " Eski evin merteği eğlen sunam eğlen<br> Ben istemem ortağı yandım sunam oy<br> Ben istemem ortağı yandım sunam oy<br> Ortak bana ne yapar eğlen sunam eğlen<br> Dış kapının direği yandım sunam oy<br> Dış kapının direği yandım sunam oy<br> Kaldır kolun oynasın sür cezveler kaynasın<br> Yârini seven oğlan gençliğine doymasın<br> Kaldır kolun oynasın sür cezveler kaynasın<br> Yârini seven oğlan gençliğine doymasın<br>                                                            <br> Şu yollar uzun yollar eğlen sunam eğlen<br> Yar bana üzüm yollar yandım sunam oy<br> Yar bana üzüm yollar yandım sunam oy<br> Hakikatli yar ise eğlen sunam eğlen<br> Saklar da güzün yollar yandım sunam oy<br> Saklar da güzün yollar yandım sunam oy<br> Kaldır kolun oynasın sür cezveler kaynasın<br> Yârini seven oğlan gençliğine doymasın<br> Kaldır kolun oynasın sür cezveler kaynasın<br> Yârini seven oğlan gençliğine doymasın" },
    { title: "NAR DANESİ", lyrics: " Sevda olmasaydı da gönüle dolmasaydı<br> Sevda olmasaydı da gönüle dolmasaydı<br> Dünya neye yarardı da güzeli olmasaydı<br> Dünya neye yarardı da güzeli olmasaydı<br> Nar tanesi tanesi de seviyom nar danesi<br> Güzellerin içinde de sevdiğim bir tanesi<br> Nar tanesi tanesi de seviyom nar danesi<br> Güzellerin içinde de sevdiğim bir tanesi<br> <br> O yar zülfünü tarar da gönül dengini arar                                                       O yar zülfünü tarar da gönül dengini arar	                                          <br> Dünyada sevmeyen de ahrette neye yarar<br> Dünyada sevmeyen de ahrette neye yarar<br> Nar tanesi tanеsi de seviyom nar danesi<br> Güzеllerin içinde de sevdiğim bir tanesi<br> Nar tanesi tanеsi de seviyom nar danesi<br> Güzеllerin içinde de sevdiğim bir tanesi<br> <br> Güzel gönül gülüdür de seveni bülbülüdür<br> Sevmeyeni neyleyim de sevenim sevgilidir<br> Nar tanesi tanesi de seviyom nar danesi<br> Güzellerin içinde de sevdiğim bir tanesi<br> Nar tanesi tanesi de seviyom nar danesi<br> Güzellerin içinde de sevdiğim bir tanesi " },
    { title: "GÖNLÜM ATAŞLARA YANDI", lyrics: " Ben bu yıl yarimden ayrı düşeli<br> Her günüm bir yıla döndü gidiyor<br> <br> Yine zından oldu dünya başıma<br> Gönlüm ataşlara yandı gidiyor<br> Ömrüm boş hayale kandı gidiyor<br> Yine zından oldu dünya başıma<br> Gönlüm ataşlara yandı gidiyor<br> Ömrüm boş hayale kandı gidiyor<br>                                                        <br> Hayal meyal olmuş şu bizim eller<br> Dostun bahçesinde açılmış güller<br> Her sabah her seher öter bülbüller<br> Gönlüm ataşlara yandı gidiyor<br> Ömrüm boş hayale kandı gidiyor<br> Her sabah her seher öter bülbüller<br> Gönlüm ataşlara yandı gidiyor<br> Ömrüm boş hayale kandı gidiyor" },
    { title: "DENİZ PARÇA", lyrics: " " },
    { title: "GENÇ OSMAN", lyrics: " (Of of) Genç Osman Dediğin Bir Küçük Uşak<br> Beline Bağlamış İbrişim Kuşak (Of Of)<br> Askerin İçinde Birinci Uşak<br> Allah Allah Deyip Geçer Genç Osman (Of Of)<br> <br> (Of of) Bağdadın İçine Girilmez Yastan<br> Her Ana Doğurmaz Böyle Bir Aslan Of Of<br> Kelle Koltuğunda Geliyor Kars'tan<br> Allah Allah Deyip Geçer Genç Osman (Of Of)<br> <br> (Of of)Bağdadın Kapısın Genç Osman Açtı<br> Düşmanın Cümlesi Önünden Kaçtı (Of Of)<br> Kelle Koltuğunda Üç Gün Savaştı<br> Allah Allah Deyip Geçer Genç Osman (Of Of)<br> Allah Allah Deyip Geçer<br> Allah Allah Deyip Geçti Genç Osman (Of Of)" },
    { title: "İKİNCİ YARI", lyrics: "", tur: "sozsuz", yari: "yari" },
    { title: "MAGUSA LİMANI", lyrics: "Magusa Liman'ı limandır, liman aman amman<br> Magusa Liman'ı limandır, liman aman amman<br> Beni öldürende yoktur din iman<br> Beni öldürende yoktur din iman<br> Uyan Ali'm uyan, uyanmaz oldun<br> Yedi bıçak yarasına dayanmaz oldun<br> Uyan Ali'm uyan, uyanmaz oldun<br> Yedi bıçak yarasına dayanmaz oldun<br>                                                         <br> İskeleden çıktım yan basa basa aman amman<br> İskeleden çıktım yan basa basa aman amman<br> Magusa'ya vardım kan kusa kusa<br> Magusa'ya vardım kan kusa kusa<br> Uyan Ali'm uyan, uyanmaz oldun<br> Yedi bıçak yarasına dayanmaz oldun<br> Uyan Ali'm uyan, uyanmaz oldun<br> Yedi bıçak yarasına dayanmaz oldun" },    
    { title: "KARA TREN", lyrics: " Gözüm yolda gönlüm darda<br> Ya kendin gel yada haber yolla<br> Gözüm yolda gönlüm darda<br> Ya kendin gel yada haber yolla<br> Duyarım yazmışsın iki satır mektup<br> Vermişsin trene halini unutup<br> Duyarım yazmışsın iki satır mektup<br> Vermişsin trene halini unutup<br> Kara tren gecikir belki hiç gelmez<br> Dağlarda salınır da derdimi bilmez<br> Dumanın savurur halimi görmez<br> Gam dolar yüreğim gözyaşım dinmez<br>                                                                 <br> Yara bende derman sende<br> Ya kendin gel yada bana gel de<br> Yara bende derman sende<br> Ya kendin gel yada bana gel de<br> Duyarım yazmışsın iki satır mektup<br> Vermişsin trene halini unutup<br> Duyarım yazmışsın iki satır mektup<br> Vermişsin trene halini unutup<br> Kara tren gecikir belki hiç gelmez<br> Dağlarda salınır da derdimi bilmez<br> Dumanın savurur halimi görmez<br> Gam dolar yüreğim gözyaşım dinmez<br> Kara tren gecikir belki hiç gelmez<br> Dağlarda salınır da derdimi bilmez<br> Dumanın savurur halimi görmez<br> Gam dolar yüreğim gözyaşım dinmez" },
    { title: "MEVLAM BİR ÇOK DERT VERMİŞ", lyrics: " Mevlam birçok dert vermiş<br> Beraber derman vermiş<br> Mevlam birçok dert vermiş<br> Beraber derman vermiş<br> Bu tükenmez derdime<br> Neden ilâç vermemiş<br> Diley diley diley yar<br> Diley diley diley yar<br> Diley diley yar<br> Bu tükenmez derdime<br> Neden ilâç vermemiş<br> Diley diley diley yar<br> Diley diley diley yar<br> Diley diley yar<br>                                                    <br> Fanidir dünya fâni<br> Alır da vermez yari<br> Fanidir dünya fâni<br> Alır da vermez yari<br> Bu tükenmez derdimi<br> Tabibler de bilmedi<br> Diley diley diley yar<br> Diley diley diley yar<br> Diley diley yar<br> Bu tükenmez derdimi<br> Tabibler de bilmedi<br> Diley diley diley yar<br> Diley diley diley yar<br> Diley diley yar" },
    { title: "PINAR BAŞINDAN BULANIR", lyrics: " Pınar başından bulanır canım oy<br> İner ovayı dolanır canım oy<br> Sende çok haller bulunur canım oy<br> Dağlar duman olur<br> Çayır çimen olur<br> Ben yari görmezsem<br> Halım yaman olur<br> Halım yaman olur<br> Vay vay<br> Ben yari görmezsem<br> Halım yaman olur<br> Halım yaman olur<br> Vay vay<br> <br> Hiç ovaya inmedin mi canım oy<br> Aşk oduna yanmadın mı canım oy<br> Can yakmaya doymadın mı canım oy<br> Dağlar duman olur<br> Çayır çimen olur<br> Ben yari görmezsem<br> Halım yaman olur<br> Halım yaman olur<br> Vay vay<br> Ben yari görmezsem<br> Halım yaman olur<br> Halım yaman olur<br> Vay vay<br> Ben yari görmezsem<br> Halım yaman olur<br> Halım yaman olur<br> Vay vay" },
    { title: "BEYAZ GİYME", lyrics: " Beyaz giyme toz olur<br> Siyah giyme söz olur<br> Gel beraber gezelim<br> Muradımız tez olur<br> Salına da salına da gel, haydi Yavrum<br> Dön dolaş yine bana gel<br> Gel beraber gezelim<br> Muradımız tez olur<br> Salına da salına da gel, haydi Yavrum<br> Dön dolaş yine bana gel<br>                                                         <br> Beyaz giyme tanırlar<br> Seni yolcu sanırlar<br> Zaten bende talih yok<br> Seni benden alırlar<br> Salına da salına da gel, haydi yavrum<br> Dön dolaş yine bana gel<br> Zaten bende talih yok<br> Seni benden alırlar<br> Salına da salına da gel, haydi Yavrum<br> Dön dolaş yine bana gel" },
    { title: "O YAR GELİR", lyrics: " O yar gelir yazı da yaban gül olur yar yar<br> Gül olur yar yar<br> Gül olur<br> Yüzün görsem tutulur dilim lal olur yar yar<br> Lal olur yar yar<br> Lal olur<br> Aşka düşen divane gezer del' olur yar yar<br> Del' olur yar yar<br> Del' olur<br> Aşka düşen divane gezer del' olur yar yar<br> Del' olur yar yar<br> Del' olur<br>                                                           <br> Mezarımı derin de kazın dar olsun yar yar<br> Dar olsun yar yar<br> Dar olsun<br> Altı lale üstü de sümbül bağ olsun yar yar<br> Bağ olsun yar yar<br> Bağ olsun<br> Ben ölürsem sevdiceğim sağ olsun yar yar<br> Sağ olsun yar yar<br> Sağ olsun<br> Ben ölürsem sevdiceğim sağ olsun yar yar<br> Sağ olsun yar yar<br> Sağ olsun" },
    { title: "DOYULUR MU", lyrics: " Tatlı dile güler yüze<br> Doyulur mu doyulur mu<br> Aşkınan bakışan göze<br> Doyulur mu doyulur mu<br> <br> Tatlı dile güler yüze<br> Doyulur mu doyulur mu<br> Aşkınan bakışan göze<br> Doyulur mu doyulur mu<br> <br> Doyulur mu doyulur mu<br> Canâna kıyılır mı<br> Canâna kıyanlar<br> Hakk'ın kulu sayılır mı<br> Doyulur mu doyulur mu<br> Canâna kıyılır mı<br> Canâna kıyanlar<br> Hakk'ın kulu sayılır mı<br> <br> <br> Hem bahara hemi yaza<br> Yârin ettikleri naza<br> Yâr aşkına çalan saza<br> Doyulur mu doyulur mu<br> <br> Hem bahara hemi yaza<br> Yârin ettikleri naza<br> Yâr aşkına çalan saza<br> Doyulur mu doyulur mu<br> <br> Doyulur mu doyulur mu<br> Canâna kıyılır mı<br> Canâna kıyanlar<br> Hakk'ın kulu sayılır mı<br> Doyulur mu doyulur mu<br> Canâna kıyılır mı<br> Canâna kıyanlar<br> Hakk'ın kulu sayılır mı<br> <br> <br> Garibim geldik gitmeye<br> Muhabbetimiz bitmeye<br> Yârinen sohbet etmeye<br> Doyulur mu doyulur mu<br> <br> Garibim geldik gitmeye<br> Muhabbetimiz bitmeye<br> Yârinen sohbet etmeye<br> Doyulur mu doyulur mu<br> <br> Doyulur mu doyulur mu<br> Canâna kıyılır mı<br> Canâna kıyanlar<br> Hakk'ın kulu sayılır mı<br> Doyulur mu doyulur mu<br> Canâna kıyılır mı<br> Canâna kıyanlar<br> Hakk'ın kulu sayılır mı<br> Doyulur mu doyulur mu<br> Canâna kıyılır mı<br> Canâna kıyanlar<br> Hakk'ın kulu sayılır mı" },
    { title: "EVLERİNİN ÖNÜ BULGUR KAZANI", lyrics: " Evlerinin önü bulgur kazanı (oğlan kazanı),<br> Evlerinin önü bulgur kazanı (oğlan kazanı),<br> Herkes sever okuyanı yazanı (oğlan yazanı).<br> Herkes sever okuyanı yazanı (oğlan yazanı).<br> Kimse sevmez meyhanede gezeni (oğlan gezeni).<br> Kimse sevmez meyhanede gezeni (oğlan gezeni).<br> <br> Armut dalda kız bahçede sallanır (oğlan sallanır),<br> Yere düşer şekerlenir ballanır (oğlan ballanır).<br> <br> Denizli’nin adım adım yolları (oğlan yolları),<br> Denizli’nin adım adım yolları (oğlan yolları),<br> Açılıp sarmıyor yârin kolları (oğlan kolları).<br> Açılıp sarmıyor yârin kolları (oğlan kolları).<br> Bülbül gibi şakır gider dilleri (oğlan dilleri).<br> Bülbül gibi şakır gider dilleri (oğlan dilleri).<br> <br> <br> Armut dalda kız bahçede sallanır (oğlan sallanır),<br> Yere düşer şekerlenir ballanır (oğlan ballanır)<br> <br> Armut dalda kız bahçede sallanır (oğlan sallanır),<br> Yere düşer şekerlenir ballanır (oğlan ballanır)" },
    { title: "KESİKÇAYIR", lyrics: " Kesik çayır biçilir mi<br> Soğuk sular içilir mi<br> Bana yârdan geçti derler<br> Seven yârdan geçilir mi<br> <br> Aman desinler desinler<br> Şeker yesinler<br> Şu kız şu oğlana<br> Yanmış desinler<br> Aman ben yandım<br> Yandım yandım yandım<br> Ellerin memleketinde<br> Eylendim kaldım<br>                                                                 <br> <br> Ankara'nın tren yolu<br> Gâhi doğri gâhi doğrum<br> Canım benim anadolu<br> Gideyim mi senden gayrı<br> <br> Aman desinler desinler<br> Şeker yesinler<br> Şu kız şu oğlana<br> Yanmış desinler<br> Aman ben yandım<br> Yandım yandım yandım<br> Ellerin memleketinde<br> Eylendim kaldım<br> Aman desinler desinler<br> Şeker yesinler<br> Şu kız şu oğlana<br> Yanmış desinler<br> Aman ben yandım<br> Yandım yandım yandım<br> Ellerin memleketinde<br> Eylendim kaldım" },
    { title: "SÜPÜRGESİ YONCADAN", lyrics: " Süpürgesi yoncadan<br> Gayet beli inceden<br> Ben seni sakınırım<br> Yerdeki karıncadan<br> Hanım şaşırdın beni<br> Aşka düşürdün beni<br> Aşk adamı ağlatır<br> Dert adamı söyletir<br> Hanım şaşırdın beni<br> Aşka düşürdün beni<br> Aşk adamı ağlatır<br> Dert adamı söyletir<br>                                                                 <br> Yokuşta yoruldun mu<br> Sözüme darıldın mı<br> Ben sana yar olalı<br> Boyumca sarıldın mı<br> <br> Hanım şaşırdın beni<br> Aşka düşürdün beni<br> Aşk adamı ağlatır<br> Dert adamı söyletir<br> Hanım şaşırdın beni<br> Aşka düşürdün beni<br> Aşk adamı ağlatır<br> Dert adamı söyletir" },
    { title: "KAVURMA KOYDUM TASA", lyrics: " Kavurma koydum tasa ağam yar paşam yar <br> Doldurdum basa basa di gel gel <br> Doldurdum basa basa di gel gel <br> Benim yârim pek güzel ağam yar paşam yar <br> Azıcık boydan kısa di gel gel <br> Azıcık boydan kısa di gel gel <br> Haydi haydi hopla gel di gel gel <br> Fistanını topla gel di gel gel <br> Haydi haydi hopla gel di gel gel <br> Fistanını topla gel di gel gel <br>                                                                             <br> Bugün ayın onudur ağam yar paşam yar <br> Yüküm buğday unudur di gel gel <br> Yüküm buğday unudur di gel gel <br> Evliye gönül verme ağam yar paşam yar <br> Eve giden unutur di gel gel <br> Eve giden unutur di gel gel <br> Haydi haydi hopla gel di gel gel <br> Fistanını topla gel di gel gel <br> Haydi haydi hopla gel di gel gel <br> Fistanını topla gel di gel gel" },
    { title: "AYAŞ YOLLARI", lyrics: " Ayaş yollarından aştım da geldim <br> Boyunu boyuma ölçtüm de geldim <br> Boyunu boyuma ölçtüm de geldim <br> Yalınız yollara düştüm de geldim <br> Yandım Allah yandım yandırma beni <br> Seviyorum diyerek kandırma beni <br> Derin uykulardan kaldırma beni  <br>                                                                <br> Ayva  çiçek açmış yaz mı gelecek  <br> Gönül bu sevdadan vaz mı geçecek <br> Gönül bu sevdadan vaz mı geçecek <br> Bana ettiklerin az mı gelecek <br> Yandım Allah yandım yandırma beni <br> Seviyorum diyerek kandırma beni <br> Derin uykulardan kaldırma beni <br> Yandım Allah yandım yandırma beni <br> Seviyorum diyerek kandırma beni <br> Derin uykulardan kaldırma beni " },
    { title: "KARPUZ KESTİM ", lyrics: " Aman karpuz kestim yiyen yok <br> Aman karpuz kestim yiyen yok <br> Haydi halin nedir diyen yok <br> Yar yar aman ben yandım aman <br> Aman da o kız seni beni aldatır aman <br> Yar yar aman ben yandım aman <br> Sevdalımın gözleri de yoldadır aman <br> Yar yar aman ben yandım aman <br>                                                                  <br> Aman karpuz kestim kırmızı <br> Aman karpuz kestim kırmızı <br> Haydi şu gelen kimin kızı <br> Yar yar aman ben yandım aman <br> Aman da o kız seni beni aldatır aman <br> Yar yar aman ben yandım aman <br> Sevdalımın gözleri de yoldadır aman <br> Yar yar aman ben yandım aman <br> Sevdalımın gözleri de yoldadır aman <br> Yar yar aman ben yandım aman  " },
    { title: "MAKARAM SARI BAĞLAR ", lyrics: " Makaram sarı bağlar kız söyler gelin ağlar <br> Makaram sarı bağlar kız söyler gelin ağlar <br> Niye ben ölmüş müyem Asyam karalar bağlar <br> Niye ben ölmüş müyem Asyam karalar bağlar <br> Lö berde lö berde zülfün yüzüne perde <br> Devriyeler sardı da bizi meğer kaderim böyle <br> Devriyeler sardı da bizi meğer kaderim böyle <br>                                                               <br> Makaramda ipliğim Asyam benim kekliğim <br> Makaramda ipliğim Asyam benim kekliğim <br> Hiç aklımdan çıkmıyor tenhalarda gezdiğim <br> Hiç aklımdan çıkmıyor tenhalarda gezdiğim <br> Lö berde lö berde zülfün yüzüne perde <br> Devriyeler sardı da bizi meğer kaderim böyle <br> Devriyeler sardı da bizi meğer kaderim böyle <br> Lö berde lö berde zülfün yüzüne perde <br> Devriyeler sardı da bizi meğer kaderim böyle <br> Devriyeler sardı da bizi meğer kaderim böyle " },



  ];

  const songContainer = $('<div class="container"></div>'); // Kapsayıcı bir div eklendi
  $('music').append(songContainer); // Kapsayıcıyı body'e ekle

  songs.forEach((song, index) => {
    const songElement = $(`
        <div class="mb-3"> 
          <button class="btn custom-btn ${song.yari} btn-block" type="button" data-toggle="collapse" data-target="#collapseLyrics${index}" aria-expanded="false" aria-controls="collapseLyrics${index}">
            ${song.title}
          </button>
          <div class="collapse" id="collapseLyrics${index}">
            <div class="card ${song.tur} custom-card card-body mt-2">
            <p>
              ${song.lyrics}
              </p>
            </div>
          </div>
        </div>
      `);

    songContainer.append(songElement); // Şarkı elementini kapsayıcıya ekle
  });
});

